name: PNPM Setup

on:
  workflow_call:
    inputs:
      node_version:
        required: false
        type: string
        default: lts
      run_tests:
        required: false
        type: boolean
        default: false
      pnpm_version:
        required: false
        type: string
        default: 10.7.0
    secrets:
        GITHUB_CI_TOKEN:
          required: true

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.1.0
        with:
          version: ${{ inputs.pnpm_version }} 

      - name: Setup Node
        uses: actions/setup-node@v4.3.0
        with:
          node-version: ${{ inputs.node_version }}

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4.2.3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        shell: bash
        run: pnpm install --frozen-lockfile

      - name: Execute Tests
        if: ${{ inputs.run_tests }} == 'true'
        run: pnpm run test:ci
